-- Create least-privilege application role
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
      CREATE ROLE app_user LOGIN PASSWORD 'app_pass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
   END IF;
END$$;

-- Allow connect to target DB
GRANT CONNECT ON DATABASE votes_db TO app_user;
GRANT CREATE ON DATABASE votes_db TO app_user;

\c votes_db

-- Ensure schemas exist before granting permissions
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS votes;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS photos;

-- Schemas usage
GRANT USAGE ON SCHEMA identity TO app_user;
GRANT USAGE ON SCHEMA votes TO app_user;
GRANT USAGE ON SCHEMA audit TO app_user;
GRANT USAGE ON SCHEMA photos TO app_user;
GRANT CREATE ON SCHEMA identity TO app_user;
GRANT CREATE ON SCHEMA votes TO app_user;
GRANT CREATE ON SCHEMA audit TO app_user;
GRANT CREATE ON SCHEMA photos TO app_user;

-- Existing tables (will be empty on first init, but grant anyway)
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA identity TO app_user;
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA votes TO app_user;
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA audit TO app_user;
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA photos TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA votes TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA audit TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA photos TO app_user;

-- Future tables default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, TRUNCATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA votes GRANT SELECT, INSERT, TRUNCATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, TRUNCATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA photos GRANT SELECT, INSERT, TRUNCATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT USAGE, SELECT ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA votes GRANT USAGE, SELECT ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA photos GRANT USAGE, SELECT ON SEQUENCES TO app_user;
